DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Kysely CASCADE;
DROP TABLE IF EXISTS Kysymys CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;
DROP TABLE IF EXISTS KurssinOsallistuja CASCADE;
DROP TABLE IF EXISTS KurssinOpettaja CASCADE;
DROP TABLE IF EXISTS Tila CASCADE;